### ISSUE TITLE
Feature show all translation possibilities

### ISSUE THREAD

**Issue by ArthurGossel1** [ArthurGossel1/deep-translator-website#29] opened 2022-12-16 14:42 UTC
Button "Show all translations"

For exemple if Google Translate says : "A" for a translation, if we click on "Show all translations" we could see : 

Google, Deepl : "A" 
Pons: "Aa" 
Mymemory "Aab"

**Comment by TonyBionda** [comment] 2023-01-20 09:54
Duplicate of #24 which is done in #37, close

**Closed by TonyBionda** 2023-01-20 09:54 UTC
Labels: duplicate, enhancement
